### ISSUE TITLE
Dashboard - The first card or default one on mainnet doesn't have the account/address name displayed

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#108]
The first card or default one on mainnet doesn't have the account/address name displayed. The account/address is missing from token page first card as well.

<img width="362" alt="Screenshot 2019-03-18 at 11 21 34" src="https://user-images.githubusercontent.com/27950955/54519821-13de2080-4970-11e9-91c2-d620f70c22e1.png">

<img width="361" alt="Screenshot 2019-03-18 at 11 23 24" src="https://user-images.githubusercontent.com/27950955/54519963-45ef8280-4970-11e9-86a1-b6cef4ab89c8.png">

**Comment by krisboit** [comment]
this shoud be solved with v0.5.2
