### ISSUE TITLE
Disclaimer - A disclaimer should be displayed and accepted when user create or restore a wallet

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#109]
The user should be able to read and accept a disclaimer when he wants to create a new wallet or restore a wallet. It is highly important to save his acceptance locally in its browser. This screen is a must in order to start use Moonlet. The text used for disclaimer can be accessed on gallery and visualised here:  https://sketch.cloud/s/Ddeke/wLRRzol/play

**Comment by krisboit** [comment]
duplicate with #95
