### ISSUE TITLE
Dashboard - default account names

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#110]
After restore wallet is done, the User has the default names of the accounts: https://www.screencast.com/t/iE2Om5lgH
ETHEREUM Account 1
ZILLIQA Account 1
=> QQ1: in this screen we have both the blockchain logos in the left and the account names using the blockchain names => it's a bit redundant... 
=> QQ2: can a User change the account's names?

**Comment by krisboit** [comment]
i agree, we can replace blockchain name with network name, it would be more relevant :)

**Comment by krisboit** [comment]
Duplicate with #117
