### ISSUE TITLE
Prices not showing up

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#112]
After switching on the developer mode, the prices don't display:
https://www.screencast.com/t/UNZeZgl7KjHO
We need to see if this can be replicated and if it's related to the switch or not.

Also the 2 accounts available after import are no longer displayed...
Again to see if this can be replicated...

**Comment by krisboit** [comment]
yep, i saw that too, sometimes the api is not responding, we will have to do our version of api

**Comment by AdrianBLK** [comment]
QQ: can we have a first fix before doing a tailored api version?

For example: if the API is not responding => to take into consideration the last currency value (a simple "cache" system), is it doable? @krisboit
