### ISSUE TITLE
Add New Account - When user adds/imports new account, the dashboard content will erase and only the imported account remains

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#114]
When user adds/imports new account, the dashboard content will erase and only the added/imported account remains displayed. Please check this video for a comprehensive view of the broken user journey: https://drive.google.com/open?id=19Riwo8u-eVyLig8xl6Zd_lkBvgLNancP

**Comment by krisboit** [comment]
@i3uRi I think this should be solved, can you still reproduce it ?

**Comment by AdrianBLK** [comment]
@i3uRi can you still reproduce it?
