### ISSUE TITLE
Card Title - Replace "ETHEREUM Account 1" with "Address 1"

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#117]
Replace "ETHEREUM Account 1" with "Address 1" having the following rationale: 

- The "ETHEREUM" is self explanatory since we have both logo and currency name on the card, namely ETH
- The word "Account" doesn't describe exactly that actually the card represents. It's an address and not an account. User basically adds a new address, whether it's a moonlet, ledger or imported one.
- The number "1" should reflect the address number for each blockchain. I'm suggesting also to freeze the name of the account from "New Account" page.
- In its current version, namely "ETHEREUM Account 1", it's too long.

**Comment by krisboit** [comment]
I propose this standard:
- For Mainnet -> Account 1, Account 2 (without blockchain)
- For testnets -> Rinkeby 1, Rinkeby 2.... this way it's easier to see the testnet name

**Comment by i3uRi** [comment]
Improved version :))))

For Mainnet -> Moonlet 1, Moonlet 2 (without blockchain) ... or Ledger 1, Ledger 2, ... or Import 1, Import 2.
For testnets -> Rinkeby 1, Rinkeby 2

**Comment by i3uRi** [comment]
Testing Discord integration. Please ignore it.

**Comment by AdrianBLK** [comment]
quick question @krisboit : when creating new accounts, the names follow the rules set above, but the first time when restoring a wallet, the default accounts are "ETHEREUM Account 1" and "ZILLIQA Account 1" => can we apply the same rule here? (mainnet + testnet = remove the "ETHEREUM" and "ZILLIQA" from names)
