### ISSUE TITLE
Create Unlock Main Page

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#12]
*As a user I want to be able to unlock my wallet so that I can access and operate my assets*

1. - [ ] Display header logo
2. - [ ] Display extension name
3. - [ ] Display extension icon
4. - [ ] Display password field
5. - [ ] Display UNLOCK WALLET. When click the password should be checked by the system: (1) if correct the Dashboard should be displayed and (2) if incorrect an error message should be displayed
6. - [ ] Display RESTORE EXISTING WALLET button and on click start the relevant flow for restoring an existing wallet

[Please use this visual asset as a guideline](https://gallery.io/projects/MCHbtQVoQ2HCZTlak4tp1lmj/files/MCHbtQVoQ2HCZeKMj6IYbnAL) and and [check here Sketch Cloud prototype](https://sketch.cloud/s/95yeD)

**Comment by narcis2007** [comment]
Is someone working on this? If not I can pick it up @i3uRi @bodogaii

**Comment by i3uRi** [comment]
Not aware about anyone to pick it up. However, Tibi already implemented this https://moonlet.cryptoland.tech Perhaps you can reuse some of the work or build on top of that.

**Comment by i3uRi** [comment]
Since Tibi leads the UI, please engage with him as well.

**Comment by narcis2007** [comment]
@krisboit

**Comment by krisboit** [comment]
Hey @narcis2007, this feature is a little complicated at this moment because we have to differentiate between web and extension, and we don't have this functionality in place. If you want you can pick #6, this one is quite clear :)

**Comment by narcis2007** [comment]
Sounds good, I'll start on it soon
