### ISSUE TITLE
Balance check (or add Max Amount)

### ISSUE THREAD

**Issue by evesnow91** [cryptolandtech/moonlet#126]
If a User send an `amount` >= `balance`. The app will still send the transaction and the transaction will get rejected.

Add a check for `amount` so it will always be valid. (meaning < `balance` - `0.001 ZIL` (gas fees))

Or add a "Max Amount" button. Reference #37

**Comment by i3uRi** [comment]
@krisboit please find here the prototype for "Add all balance" feature: https://sketch.cloud/s/Ddeke/paedrmr/play . Once the hyper-text is clicked, it should change it's status into "Added + check icon"
