### ISSUE TITLE
Restore Existing Wallet - should not go to password screen if secret phase is empty

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#129]
When on Restore Existing Wallet screen and the user leaves empty the "secret phrase" area it, it should not be possible to advance to the next screen (demading the password)
=> an error message should appear bellow the "secret phrase" area: Invalid mnemonic (to keep it consistent with the other error message if the mnemonic is not validated)

**Comment by AdrianBLK** [comment]
I was able to do the following steps:
Restore Existing Wallet
leave empty secret phrase
enter a password
click on CREATE PASSWORD 
=> it goes to the dashboard screen
=> how is everything created without any secret phrase?!? @krisboit

**Comment by krisboit** [comment]
It generates one :))

**Comment by krisboit** [comment]
Nice bug :))

**Comment by AdrianBLK** [comment]
Doing the same steps (Restore Existing Wallet -> leave empty secret phrase -> enter the SAME password -> click on CREATE PASSWORD) gets stuck on the last screen (no errors, no dashboard)

But, after closing the extension and opening it again, I'm logged in to the default Dasboard
(as it connects me to the accounts created earlier)
