### ISSUE TITLE
Dashboard open new tab - then open new tab again - dashboard not ok 

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#131]
In extended view, dashboard screen, if the user clicks on Settings -> Open new tab, the new windows is an empty Dashboard.
Video example here: https://www.screencast.com/t/KzommBTKPvi

**Comment by AdrianBLK** [comment]
After this issue, the default Dashboard is empty on refresh (both in extended view and regular extension view).

**Comment by AdrianBLK** [comment]
Also after this issue, in extended view, after signout, the signin has a little issue, not going to the default dashboard.
But it goes to the dashboard after click on RESTORE WALLET.
Video example here: https://www.screencast.com/t/IN9kjVOOS

**Comment by krisboit** [comment]
@AdrianBLK i couldn't reproduce the issue, can you please check the console when the issue happens and check if there are any errors. Thanks.
