### ISSUE TITLE
[Bug] Transaction history corrupted

### ISSUE THREAD

**Issue by evesnow91** [cryptolandtech/moonlet#134]
When I did a transaction on an imported account (my mining account) to my HD generated account, the transaction history appeared in my HD generated account page.

![Capture](https://user-images.githubusercontent.com/31395583/55568385-31620700-5732-11e9-8f78-a9f3284ce3e9.PNG)
![Capture2](https://user-images.githubusercontent.com/31395583/55568389-32933400-5732-11e9-8934-777809915c59.PNG)

**Comment by krisboit** [comment]
@evesnow91 did the transaction appear on the other wallet (0xB2E51878722D8B6D2C0F97E995A7276D64C1618B) also ?

Can you please send me a screenshot from transaction details, the transaction from the first screenshot. 

Thanks.

**Comment by evesnow91** [comment]
No, the other wallet did not send out the transactions.

I will post the screenshot later as it is on my home computer.
However, this was the transaction in question:
https://viewblock.io/zilliqa/tx/d69d3370e12235f570abd94be858e0bf658559bec26dafea74172faf30cd416e

**Comment by krisboit** [comment]
@evesnow91 can you reproduce this issue ? 
We couldn't.

**Comment by krisboit** [comment]
@evesnow91 i will close this issue, as there are no updates. Please reopen it if you can reproduce the problem.
