### ISSUE TITLE
First install - Create new wallet and restore existing wallet buttons don't work

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#136]
After I have installed 0.5.8., `Create new wallet` and `Restore existing wallet` buttons don't work. If I'm closing the extension and then opening again, both works properly. There are some errors in the console as well. Please check them below:
<img width="1676" alt="Screenshot 2019-04-05 at 08 51 42" src="https://user-images.githubusercontent.com/27950955/55606168-76148f00-5780-11e9-9297-9a12202803b4.png">

**Comment by AdrianBLK** [comment]
seems to be fixed now (on my side, on v.05.10)
