### ISSUE TITLE
Account names should be unique (to avoid possible confusions)

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#138]
Steps to reproduce:
- add three accounts (from Moonlet) on the same blockchain (for example ETHEREUM Account 1, Account 2 and Account 3)
- discard Account 2
- add new account -> select the same blockchain (Ethereum) => the screen suggests the name "ETHEREUM Account 3" although there is an account with the same name in the dashboard list
=> is there a quick fix for this one?

Video here: https://www.screencast.com/t/9eQ21pf9

**Comment by i3uRi** [comment]
This is still reproducing. I discarded 2 accounts and added 2 more. As you can see below, I succeeded to add 2 new accounts with the same account name. However, I'm not going to keep the critical label since the user can edit account/address name.

**Comment by krisboit** [comment]
@i3uRi just wait for the next release ;)
