### ISSUE TITLE
[UD] As a User I want to have an option to buy a .zil domain name from the header Context Menu

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#146]
In the header's Context Menu add a new menu item with:
- the following text: "Get your .zil domain" + the basket icon
- onclick on this new menu item it opens in a new tab the partnership link: **_TBD_**

Visual updates here: https://www.screencast.com/t/YssumcDsAmt

**Comment by krisboit** [comment]
#153 contains this issue
