### ISSUE TITLE
Chrome extension requests permission to read browsing history

### ISSUE THREAD

**Issue by pinwc4** [cryptolandtech/moonlet#161]
When attempting to install the Chrome extension a popup warns users that this extension requires permission to "Read your browsing history"

<img width="433" alt="Screen Shot 2019-04-16 at 10 52 27 AM" src="https://user-images.githubusercontent.com/6935382/56226548-1304e100-6039-11e9-8c9f-c37fc904647b.png">

This may be triggered from requesting Tabs permissions.  By requiring these permissions your extension can read the url of any opened tab.  Please either remove the tabs requirement or make it optional.

**Comment by krisboit** [comment]
Hey @pinwc4,

We know about the issue. The `tabs` permission is used for a feature that is making users aware that are interacting with Moonlet Wallet not a fake webpage. We are working to implement that feature without `tabs` permission.

I will come back with updates here.

Thanks for the feedback.

**Comment by i3uRi** [comment]
@pinwc4 an update with fixes for both firebase and tab permission issues has been pushed live in Chrome Store. The update process should be smoother now. :)

**Comment by pinwc4** [comment]
Thanks for all your work, it looks good

**Comment by i3uRi** [comment]
@pinwc4 it would help us a lot to have your feedback on Chrome Store, as a review or comment. Thanks so much. :)
