### ISSUE TITLE
toBench32

### ISSUE THREAD

**Issue by AndreiD** [cryptolandtech/moonlet#171]
baietzii, 
voi cand aveti de gand sa faceti update la  `Bech32` address format la ZIL ?

daca.... aveti de gand sa faceti

sau v-au taiat baietzii fundingu ?

sal

PS. feedback da eroare 500.!!! NU POT SA FOLOSESC Contact us de pe siteul vostru!!! 

deci nu poti sa te ocupi de crypto, daca un formular de contact nu merge :))) va rog sa il fixati, sa nu imi fie rusine ca am cetatzenie romana..

**Comment by AndreiD** [comment]
acum mi-a zis unu ca aveti update. dar puneti si voi un blog post, faceti update la imaginile de pe site cu vechile adrese...sa vada toti ca aveti update la wallet,..... 

ce rost are sa muncesti daca nu te lauzi!

**Comment by i3uRi** [comment]
Am extras tot ce era pozitiv din mesajul tau, @AndreiD. Astfel, chiar iti multumim pentru feedback. Mi-a fost greu sa ii gasesc latura constructiva, mi-a luat ceva, trebuie sa admit, dar de folos, totusi. 👍 

O sa investigam ce este in neregula cu contact formul acela. O sa actualizam si imaginile de pe website. Ne-au scapat, dar este foarte buna sugestia. Si de laudat ne laudam, doar ca pe Twitter, Telegramul Zilliqa, etc. Da si tu un follow aici https://twitter.com/moonlet_wallet/status/1132825281058598912

Anyway, noi speram sa folosesti in continuare walletul nostru, iar daca te va determina vreodata sa iti schimbi cetatenia, sa ne dai de veste de urgenta. Mai rezolvam un bug, doua si in final ramanem conationali, chiar si prieteni. :)))))))))
