### ISSUE TITLE
Restore Existing Wallet - Invalid mnemonic

### ISSUE THREAD

**Issue by mickys** [cryptolandtech/moonlet#20]
Entering a word that is not present in the mnemonic store, triggers an error.

We need to implement Error reporting / notifications on this step.

Should display the error message before asking for password creation.

![screen shot 2018-10-15 at 11 37 30](https://user-images.githubusercontent.com/200507/46939345-b9fac700-d06e-11e8-9d9d-8faa01757a2a.png)

![screen shot 2018-10-15 at 11 33 56](https://user-images.githubusercontent.com/200507/46939212-65efe280-d06e-11e8-8e48-9caa9ffaef14.png)

**Comment by krisboit** [comment]
fixed with commit 9a6308c0149428e8e758c4e971ab1683d48a0caf
