### ISSUE TITLE
Dashboard: Account balance card improvements

### ISSUE THREAD

**Issue by krisboit** [cryptolandtech/moonlet#29]
1. Right now we display '...' as a loader, wich is crapy :). We should integrate a loader component.

Material design component doesn't have a circular loader implemented yet, but there are some unofficial implementation that we could use: https://codepen.io/mrrocks/pen/EiplA

2. We should display a refresh button, to give the user the option to refresh the balance.

**Comment by mickys** [comment]
As long as we don't over do it with the crazy flashy fade / jump stuff, we're golden 👍
