### ISSUE TITLE
Send Page: Confirm button on web-mobile layout issue

### ISSUE THREAD

**Issue by bodogaii** [cryptolandtech/moonlet#39]
Confirm button on web-mobile (SendPage) disappears under the bottom bar when no recipient and amount is set.

**Comment by krisboit** [comment]
I just realised what's the real problem here. It seems that bottombar comes over the content, we need a padding on body. I will create a separate issue to describe the problem. 

Your changes are not in vain, you optimised the send page, now confirm button will be on screen on every devices.
