### ISSUE TITLE
[Google Docs List] Critical - Issue with restoring a wallet. Once I log out, and click restore wallet, the key phase is still there

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#58]
Critical - Issue with restoring a wallet. Once I log out, and click restore wallet, the key phase is still there!

[Screenshot 2019-01-23 at 10.50.35.png](https://images.zenhubusercontent.com/5b72918402b9fd36cfbf71b4/22610053-88a1-4946-9944-2dfa7087b1e8)

**Comment by krisboit** [comment]
a45ee040a265608722b72bfb2204282b05c9a4c3 is fixing this.
