### ISSUE TITLE
Create New Wallet Page

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#6]
*As a user I want to be able to access a Create New Wallet page when I click Accept terms button from main page so that I can start to create a new wallet*

- [ ] The page should be triggered when user accepts terms from main page dialog box
- [ ] The page should animate from bottom as in the demo (see below)
- [ ] The page should animate from top when user clicks close button

 The page will have the following structure:
- [x] Page title "Create New Wallet"
- [x] Page close button
- [x] Stepper number
- [x] Journey step title

- [x] Secret phrase
- [x] Hidden secret phrase
- [x] Revealed secret phrase

- [x] Backup tips
- [x] Call to action buttons

Please [use this visual asset as a guideline](https://gallery.io/projects/MCHbtQVoQ2HCZTlak4tp1lmj/files/MCHbtQVoQ2HCZeKMj6IYbnAL) and [check the prototype on Sketch Cloud](https://sketch.cloud/s/95yeD)

**Comment by narcis2007** [comment]
@i3uRi You can assign this to me. I'm going to implement the logic behind this after I finish the UI part
