### ISSUE TITLE
[Google Docs List] High - Log contain secret phase

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#60]
High - Log contain secret phase
![Screenshot 2019-01-23 at 10.53.02.png](https://images.zenhubusercontent.com/5b72918402b9fd36cfbf71b4/dbbdaae9-167c-4b07-a25e-db4d8c333387)

**Comment by krisboit** [comment]
9cfd44bb4b6ddf1f948ad97ed9d93a99b96197a0 solves this one
