### ISSUE TITLE
[Slack List 1] LOW moonlet-core dependencies

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#61]
- LOW moonlet-core dependencies
    - a dependency of moonlet-core is susceptible to a denial of service attack: `mem`
    - for details please see https://snyk.io/test/github/cryptolandtech/moonlet-core and https://snyk.io/vuln/npm:mem:20180117

**Comment by krisboit** [comment]
1c9bab3a09d7711af4dde0e671988473b2f80902 fixes this one
