### ISSUE TITLE
[Slack List 1] MEDIUM moonlet-core and moonlet

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#62]
MEDIUM moonlet-core and moonlet
    - moonlet-core and moonlet have many dependencies that are fetched from public repositories. For security critical software I recommend a vendoring approach instead                                    
    - rationale: in the past attackers were able to take over projects on npmjs, thus enabling them to spread malicious code (please see `event-stream / flatmap-stream` incident)
    - possible mitigations:                                                                           
        - minimal: use fixed versions in your `package.json`, instead of allowing minor version upgrades. This also ensures repeatable builds without relying on a lock file                                
        - better: vendor all dependencies and do a code review
        - integrate a service like snyk.io (or any similar service) into your build system to scan automatically for vulnerabilities in dependencies

**Comment by krisboit** [comment]
For Moonlet repo:
- fixed versions were set for the dependencies in package.json

We will integrate snyk.io at build time to detect vulnerabilities.

**Comment by krisboit** [comment]
For Moonlet-core repo:

- fixed versions were set for the dependencies in package.json
- moved unimportant dependencies to devDependencies section

**Comment by krisboit** [comment]
e5f22fb804fec5937b84da6803a61082e5bc25ff - snyk.io was integrated in travis ci build
> moonlet@0.3.0 snyk /home/travis/build/cryptolandtech/moonlet
> snyk test
Testing /home/travis/build/cryptolandtech/moonlet...
Organisation:      krisboit
Package manager:   npm
Target file:       package-lock.json
Open source:       no
Project path:      /home/travis/build/cryptolandtech/moonlet
✓ Tested 179 dependencies for known vulnerabilities, no vulnerable paths found.
