### ISSUE TITLE
[Slack List 1] NONE Moonlet Wallet ( https://moonlet.cryptoland.tech/ )

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#63]
NONE Moonlet Wallet ( https://moonlet.cryptoland.tech/ )
    - by design the wallet restricts the attack surface very well. The app has no local storage (no cookies, no local storage, no session storage) 
        - as such CSRF attacks are not possible
        - note: the extension uses local storage, though there CSRF does not apply
    - the wallet uses React. React mitigates XSS attacks unless the function `dangerouslySetInnerHTML` is used. The Moonlet wallet does not use this function, thus XSS is not possible. 
        - recommendation: add automation (pre-commit hook or similar) to prevent the use of this function

**Comment by krisboit** [comment]
Some of the items are not relevant since we decommissioned. 

5d484eac97aa094f99638bed05559a3f49d10324  Added pre-comit hook to prevent `dangerouslySetInnerHTML` function usage.
