### ISSUE TITLE
[Slack List 1] MEDIUM Moonlet Wallet ( https://moonlet.cryptoland.tech/ )

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#64]
MEDIUM Moonlet Wallet ( https://moonlet.cryptoland.tech/ )
    - general issue: HTTP security headers are missing
    - HSTS: enforces strict transport security. After once visiting the page via HTTPS any future HTTP requests will be prevented, thus making man-in-the-middle attacks much harder
    - X-Frame-Options: prevents embedding of the wallet as a frame, prevents against clickjacking attacks
    - X-XSS-Protection: enables XSS protection if supported by the browser
    - these three are a good start; more headers can be found here: https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers

**Comment by krisboit** [comment]
this is not relevant since we decommissioned the web wallet
