### ISSUE TITLE
[Slack List 1] CRITICAL the extension manifest defines web accessible resources

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#65]
CRITICAL https://github.com/cryptolandtech/moonlet/blob/6ca1aff778d5f4528cdb2de13371c27324fc6099/src/extension/manifest.json#L25
    - the extension manifest defines web accessible resources, this might allow other code (web pages or extensions) to access the wallet
    - this feature should be switched off, if possible

**Comment by krisboit** [comment]
43279330702b47bf45270d873e22efdce87e5fd3  `web-inject.js` was used to facilitate web-extension integration. For now we have disabled the integration because of long review times.
