### ISSUE TITLE
[Slack List 2] threat model

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#66]
From a threat modeling perspective the wallet as a browser extension is inherently fairly secure. There are not many attack vectors:
1) local storage can be attacked, but the wallet is stored AES256-CBC encrypted using a key derived from the password. This is likely good enough given that a local attacker can do much worse (modify the browser, intercept key presses etc.)
2) XSS is not possible due to use of react (assuming all HTML is generated via react, which I have not yet verified)
3) interaction with the wallet can be restricted to the browser user (see issue above, disable web access)
4) network interaction is thus the remaining attack surface. Here simple measures like enforcing HTTPS in the wallet code, maybe ensuring certain HTTP security headers are set and similar mitigations shou
ld give a sufficient high level of security when talking to API endpoints.

Excluded from this threat model are attacks on the browser itself. This remains as an inherent weakness, but I assume this risk is simply accepted.
Also excluded from this threat model are any trust issues with the Zilliqa network API endpoint.

One idea remains: One could think about changing the wallet to allow access to the public key without logging in. I believe users more often check there balances than they do transactions. This would protect the private key better, since it would not stay as often in browser memory.

**Comment by krisboit** [comment]
3. web wallet is already decommissioned
4. API endpoints are hardcoded in wallet code and we use https everywhere, the HTTP security headers should be set by APIs (it's not in our control)

The idea to keep the private keys in memory only when needed is very good, but it would radically change the design of our app. We will keep this idea in mind and will try to achieve this goal in future.
