### ISSUE TITLE
Decomission Web Wallet https://moonlet.cryptoland.tech

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#67]
It doesn't make sense to keep web wallet since the web approach has so many vulnerabilities. Therefore the web wallet is going to be decommissioned and the focus would be on the extension only, at least for now.

**Comment by krisboit** [comment]
- moonlet.cryptoland.tech DNS entry was removed (https://dnschecker.org/#A/moonlet.cryptoland.tech)
- web build in travis was disabled 0f95a4f0e24773e8c72f0fc68217955d94bfc2e9
- all deployments in firebase were deleted
