### ISSUE TITLE
Token Page - Reveal public key doesn't work

### ISSUE THREAD

**Issue by i3uRi** [cryptolandtech/moonlet#81]
It looks that the password created on wallet initialisation doesn't work to reveal the **public** key of a specific address. I noticed that when I click the CTA button the last character from the password is removed and the error message is displayed. 

NOTE: The same password works properly on Sign In.

**Comment by AdrianBLK** [comment]
The issues #80 #81 #88 are related / similar.

**Comment by AdrianBLK** [comment]
@krisboit if you put the correct password plus an additional character, then it works (the extra character is removed in the process) :)
