### ISSUE TITLE
Expand view - Account screen - display issue

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#90]
In expand view, on the Account screen (click on any card in the Dashboard), we have a display issue with the right column / the account: https://www.screencast.com/t/E88GMt8W4z

**Comment by i3uRi** [comment]
My suggestion is to have already the first address selected and remove one click. Now you have to click to select the address. Also a new bug was introduced on drop down menu from the address card. It's not completely visible.
