### ISSUE TITLE
Dashboard - default account name missing

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#91]
After new wallet creation, the "Account 1" name is missing: https://www.screencast.com/t/a37alnIMk
(although the account was created by Moonlet as first account)

**Comment by i3uRi** [comment]
This issue still persist. The first default account added doesn't have its name displayed, namely _Account 1_. I'm going to reopen it.

**Comment by i3uRi** [comment]
This issue still persist. The first default account added doesn't have its name displayed, namely Account 1. I'm going to reopen it.
