### ISSUE TITLE
Dashboard on testnets - should display a default card / account for ZIL and ETH

### ISSUE THREAD

**Issue by AdrianBLK** [cryptolandtech/moonlet#94]
After switching on testnets, the dashboard should have:
- a first ETH card / account
- a first ZIL card / account 
- the (+) add account option

(when a User switches the first time on testnets the dasboard is empty: https://www.screencast.com/t/a52ySbaJS )

For all accounts created in testnet config the name should beging with "Test Account " and then the number (1,2,3...)

**Comment by AdrianBLK** [comment]
QQ: on testnets should the accounts have the same default names? (Account 1, Account 2, ...) isn't confusing with the mainnets? or should we have "Test Account 1"?

**Comment by i3uRi** [comment]
Agree. It's much more relevant since the accounts/addresses on testnets will differ than on mainnet.
